### ISSUE TITLE
PC freezes and displays login screen

### ISSUE THREAD

**Issue by meisme-dev** [chironjit/single-gpu-passthrough#2]
I have an HP Prebuilt Omen 30L with an Nvidia RTX 2070 Super and an AMD Ryzen 7 3700X.

**Comment by meisme-dev** [comment]
I checked logs, nothing useful:
```
[meisme@nixos:~]$ sudo cat /var/log/libvirt/qemu/win10.log
[sudo] password for meisme: 
2021-10-11 17:12:05.360+0000: shutting down, reason=failed

[meisme@nixos:~]$  
```

**Comment by meisme-dev** [comment]
![image](https://user-images.githubusercontent.com/49573906/136829460-2ff5b8ae-d1d1-4254-b808-ec093e1ebecf.png)
I disabled the hooks to see what's wrong, got this error.

**Comment by meisme-dev** [comment]
I managed to solve all this but I have a new problem. My monitor goes black for a few seconds, then freezes on the login screen (no blinking cursor, tty switching doesn't work): 
![image](https://user-images.githubusercontent.com/49573906/136861233-e8007496-9b27-4c59-97af-ee09b5183444.png)

**Comment by meisme-dev** [comment]
![image](https://user-images.githubusercontent.com/49573906/136869092-4d2dfc45-9631-4404-93cf-c1e683ff54eb.png)
Looks like the GPU modules aren't getting unloaded for some reason

**Comment by chironjit** [comment]
Hey, what is your motherboard chipset? The usual issue is that your motherboard doesn't properly support IOMMU and thus fails to unbind the GPU. The error you posted does indeed look like this is the case.

**Comment by chironjit** [comment]
On checking the interwebs, the HP Omen box comes with a b450 motherboard. b450 chipsets do not have proper IOMMU support and you'll have to use an ACS patch. I'd suggest visiting Bryan Steiner's guide (check the Credits section) and using the ACS patch guide from there (don't forget to read the whole section, including why its not recommended, before proceeding).

Once you have correctly implemented the ACS patch, you should be able to follow the rest of the guide here.

As a note to anyone else looking, it is not recommended that you try GPU passthrough on b450, b550 chipsets - implementation of IOMMU requires both chipset, bios and motherboard vendor support. This is something that most vendors do not bother with in mid to lower tier chipsets, as well as the general knowledge that support of passthrough on ASMedia (the actual IP / designers of the b450, b550 chipsets) is bad.

To note, even with the settings enabled, I had failed to passthrough a hardware device on b450 without using the ACS patch. This guide is based on an X570 chipset.

**Comment by meisme-dev** [comment]
Thanks for the quick reply! I applied the ACS patch, and IOMMU seems to be working correctly. Still failed PCI passthrough unfortunately. I don't think there's anyway I can fix it.
![Screenshot_20211013_165449](https://user-images.githubusercontent.com/49573906/137211215-c4b2d787-17ec-42f7-9956-268b3b4f9d7f.png)

**Comment by meisme-dev** [comment]
I fixed it! SDDM wasn't shutting down properly, which caused the problem.
